### PR TITLE
Remove TestFlightServiceExtension and Background Location monitor

### PR DESCRIPTION
**Pull request by JJTech0130**
Honestly, it was always unreliable and isn't worth the extra effort to maintain.
Also removes the background location permission.

Added a "Keep Awake" option that keeps the screen on as a better alternative to both.

### CODE REVIEW

**Comment by JJTech0130** [comment]
I reworked the reconnection logic to hopefully fix the issues encountered in #9 

I've attached a build, note that this has not been tested on a real device yet so I would appreciate any feedback.
[ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17525410/ValidationRelay.tipa.zip)

**Comment by theol0403** [comment]
Thanks for working on this! The dim button is working, and I'd assume the keep awake is too. It worked with openbubbles as well. 

I did experience one freeze and two crashes in validation relay, as well as a few failed attempts to connect to the relay server. However, my internet is being shitty, so not sure if this is new or not. I'd recommend stress-testing yourself more before releasing.

**Comment by JJTech0130** [comment]
I think that is a limitation of iOS? I read somewhere that if the user overrides the brightness your app sets you're not allowed to set it again.

**Comment by JJTech0130** [comment]
re: the crash, do you happen to have the crash log? You can find it in the analytics settings iirc.

**Comment by theol0403** [comment]
@JJTech0130 doesn't seem to be too much useful stuff in here, especially since I've restarted the app a few times since then but didn't see anything else related to validation relay in analytics

[ValidationRelay-2024-10-25-142054.txt](https://github.com/user-attachments/files/17525763/ValidationRelay-2024-10-25-142054.txt)

**Comment by JJTech0130** [comment]
Ah, I think I see what happened: it was about to attempt a reconnection (it was in the backoff period) when you turned off the toggle switch.

**Comment by theol0403** [comment]
Nevermind I found some better dumps: 
[stacks+ValidationRelay-2024-10-25-141723.txt](https://github.com/user-attachments/files/17525812/stacks%2BValidationRelay-2024-10-25-141723.txt)

**Comment by JJTech0130** [comment]
See if this build fixes your issues
[ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17526068/ValidationRelay.tipa.zip)

**Comment by theol0403** [comment]
So far so good!

**Comment by mackid1993** [comment]
> See if this build fixes your issues [ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17526601/ValidationRelay.tipa.zip)

@JJTech0130 Is this the final 1.8 release? Just curious since when I install on my iPhone I seem to have to enter a new code.

**Comment by JJTech0130** [comment]
Were you using the TestFlight version before? It in theory should have migrated seamlessly if not, but their might have been an issue with how the old version was signed, not sure.

**Comment by mackid1993** [comment]
Yes. I was using the testflight version so when I went to install todays build I had a second app.

--
David Brustein

**Comment by theol0403** [comment]
Yeah, migrating from the testflight version to the first build posted here created a second listing in the trollstore app and the validation code was changed.

**Comment by cameronaaron** [comment]
I wanted to brush up my swift skills so I decided to try and fix the things in my review myself :) Feel free to cherry pick what you feel is helpful if anything https://github.com/JJTech0130/ValidationRelay/pull/12

**Comment by mackid1993** [comment]
@JJTech0130 The relay has been solid for me all weekend! It's reconnected a couple of times according to the logs. At one point I even shut WiFi off for a 30-45 seconds and it recovered just fine. Thanks so much for fixing this. I'm sure you're super busy with college applications and such so I really do appreciate your taking the time to fix this for us all!! 🙂 Good luck!

**Comment by JJTech0130** [comment]
[ValidationRelay.tipa.zip](https://github.com/user-attachments/files/17543060/ValidationRelay.tipa.zip)
Slightly modified build with capped maximum backoff time.
Backoff time should also reset if you toggle it off and on manually.

**Comment by mackid1993** [comment]
If something really breaks like the Internet goes out for a while and then comes back...will it still eventually reconnect even with the maximum backoff?

--
David Brustein

**Comment by JJTech0130** [comment]
Yes, the maximum backoff means that it will retry at minimum about once per minute, rather than continuing to grow exponentially (meaning it might not retry until a long time after connectivity is restored

**Comment by mackid1993** [comment]
I did run into an issue yesterday. I opened up openbubbles, no messages were showing up. I got kicked to the setup screen and had to re-register my phone number which worked just fine... I logged back in with my apple ID and everything was fine afterwards. I did update to the latest tipa so logs may be lost, but I thought I should report it. Not sure if I can provide any helpful info other than what happened.

**Comment by mackid1993** [comment]
It may have been an Apple or OB issue because I just looked and I don't have two iPhones linked to my Apple ID now. Just the one still.

**Pull request merged**
